# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: almacen/rpc/cluster.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'almacen/rpc/cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61lmacen/rpc/cluster.proto\x12\x07\x61lmacen\"\xa3\x01\n\rFileRecordMsg\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_hash\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x11\n\ttombstone\x18\x05 \x01(\x08\x12\x14\n\x0ctombstone_at\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x12\n\nupdated_at\x18\x08 \x01(\t\"\x1f\n\x0cReplicateAck\x12\x0f\n\x07\x61pplied\x18\x01 \x01(\x08\"#\n\x0bPingRequest\x12\x14\n\x0c\x66rom_node_id\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t2\x80\x01\n\x07\x43luster\x12@\n\x0fReplicateRecord\x12\x16.almacen.FileRecordMsg\x1a\x15.almacen.ReplicateAck\x12\x33\n\x04Ping\x12\x14.almacen.PingRequest\x1a\x15.almacen.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'almacen.rpc.cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILERECORDMSG']._serialized_start=39
  _globals['_FILERECORDMSG']._serialized_end=202
  _globals['_REPLICATEACK']._serialized_start=204
  _globals['_REPLICATEACK']._serialized_end=235
  _globals['_PINGREQUEST']._serialized_start=237
  _globals['_PINGREQUEST']._serialized_end=272
  _globals['_PINGRESPONSE']._serialized_start=274
  _globals['_PINGRESPONSE']._serialized_end=305
  _globals['_CLUSTER']._serialized_start=308
  _globals['_CLUSTER']._serialized_end=436
# @@protoc_insertion_point(module_scope)
