# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from almacen.rpc import cluster_pb2 as almacen_dot_rpc_dot_cluster__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in almacen/rpc/cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplicateRecord = channel.unary_unary(
                '/almacen.Cluster/ReplicateRecord',
                request_serializer=almacen_dot_rpc_dot_cluster__pb2.FileRecordMsg.SerializeToString,
                response_deserializer=almacen_dot_rpc_dot_cluster__pb2.ReplicateAck.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/almacen.Cluster/Ping',
                request_serializer=almacen_dot_rpc_dot_cluster__pb2.PingRequest.SerializeToString,
                response_deserializer=almacen_dot_rpc_dot_cluster__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Gossip = channel.unary_unary(
                '/almacen.Cluster/Gossip',
                request_serializer=almacen_dot_rpc_dot_cluster__pb2.GossipDigest.SerializeToString,
                response_deserializer=almacen_dot_rpc_dot_cluster__pb2.GossipDelta.FromString,
                _registered_method=True)


class ClusterServicer:
    """Missing associated documentation comment in .proto file."""

    def ReplicateRecord(self, request, context):
        """Phase 2: direct push of a metadata record to a peer. Phase 4's push-pull
        anti-entropy supersedes this as the repair mechanism, but this stays as the
        fast path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Gossip(self, request, context):
        """Push-pull anti-entropy: the caller advertises what it has, the
        responder replies with what it should send and what it wants back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplicateRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateRecord,
                    request_deserializer=almacen_dot_rpc_dot_cluster__pb2.FileRecordMsg.FromString,
                    response_serializer=almacen_dot_rpc_dot_cluster__pb2.ReplicateAck.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=almacen_dot_rpc_dot_cluster__pb2.PingRequest.FromString,
                    response_serializer=almacen_dot_rpc_dot_cluster__pb2.PingResponse.SerializeToString,
            ),
            'Gossip': grpc.unary_unary_rpc_method_handler(
                    servicer.Gossip,
                    request_deserializer=almacen_dot_rpc_dot_cluster__pb2.GossipDigest.FromString,
                    response_serializer=almacen_dot_rpc_dot_cluster__pb2.GossipDelta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'almacen.Cluster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('almacen.Cluster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cluster:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReplicateRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almacen.Cluster/ReplicateRecord',
            almacen_dot_rpc_dot_cluster__pb2.FileRecordMsg.SerializeToString,
            almacen_dot_rpc_dot_cluster__pb2.ReplicateAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almacen.Cluster/Ping',
            almacen_dot_rpc_dot_cluster__pb2.PingRequest.SerializeToString,
            almacen_dot_rpc_dot_cluster__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Gossip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almacen.Cluster/Gossip',
            almacen_dot_rpc_dot_cluster__pb2.GossipDigest.SerializeToString,
            almacen_dot_rpc_dot_cluster__pb2.GossipDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
