# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from almacen.rpc import replication_pb2 as almacen_dot_rpc_dot_replication__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in almacen/rpc/replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationStub:
    """Blob transfer between nodes. Content is streamed because a blob can be far
    larger than gRPC's 4 MiB default message limit.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutBlob = channel.stream_unary(
                '/almacen.Replication/PutBlob',
                request_serializer=almacen_dot_rpc_dot_replication__pb2.BlobChunk.SerializeToString,
                response_deserializer=almacen_dot_rpc_dot_replication__pb2.PutBlobAck.FromString,
                _registered_method=True)
        self.GetBlob = channel.unary_stream(
                '/almacen.Replication/GetBlob',
                request_serializer=almacen_dot_rpc_dot_replication__pb2.BlobRequest.SerializeToString,
                response_deserializer=almacen_dot_rpc_dot_replication__pb2.BlobChunk.FromString,
                _registered_method=True)


class ReplicationServicer:
    """Blob transfer between nodes. Content is streamed because a blob can be far
    larger than gRPC's 4 MiB default message limit.
    """

    def PutBlob(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutBlob': grpc.stream_unary_rpc_method_handler(
                    servicer.PutBlob,
                    request_deserializer=almacen_dot_rpc_dot_replication__pb2.BlobChunk.FromString,
                    response_serializer=almacen_dot_rpc_dot_replication__pb2.PutBlobAck.SerializeToString,
            ),
            'GetBlob': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBlob,
                    request_deserializer=almacen_dot_rpc_dot_replication__pb2.BlobRequest.FromString,
                    response_serializer=almacen_dot_rpc_dot_replication__pb2.BlobChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'almacen.Replication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('almacen.Replication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replication:
    """Blob transfer between nodes. Content is streamed because a blob can be far
    larger than gRPC's 4 MiB default message limit.
    """

    @staticmethod
    def PutBlob(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/almacen.Replication/PutBlob',
            almacen_dot_rpc_dot_replication__pb2.BlobChunk.SerializeToString,
            almacen_dot_rpc_dot_replication__pb2.PutBlobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/almacen.Replication/GetBlob',
            almacen_dot_rpc_dot_replication__pb2.BlobRequest.SerializeToString,
            almacen_dot_rpc_dot_replication__pb2.BlobChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
