# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: almacen/rpc/replication.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'almacen/rpc/replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61lmacen/rpc/replication.proto\x12\x07\x61lmacen\"/\n\tBlobChunk\x12\x14\n\x0c\x63ontent_hash\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"2\n\nPutBlobAck\x12\x14\n\x0c\x63ontent_hash\x18\x01 \x01(\t\x12\x0e\n\x06stored\x18\x02 \x01(\x08\"#\n\x0b\x42lobRequest\x12\x14\n\x0c\x63ontent_hash\x18\x01 \x01(\t2z\n\x0bReplication\x12\x34\n\x07PutBlob\x12\x12.almacen.BlobChunk\x1a\x13.almacen.PutBlobAck(\x01\x12\x35\n\x07GetBlob\x12\x14.almacen.BlobRequest\x1a\x12.almacen.BlobChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'almacen.rpc.replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOBCHUNK']._serialized_start=42
  _globals['_BLOBCHUNK']._serialized_end=89
  _globals['_PUTBLOBACK']._serialized_start=91
  _globals['_PUTBLOBACK']._serialized_end=141
  _globals['_BLOBREQUEST']._serialized_start=143
  _globals['_BLOBREQUEST']._serialized_end=178
  _globals['_REPLICATION']._serialized_start=180
  _globals['_REPLICATION']._serialized_end=302
# @@protoc_insertion_point(module_scope)
